#!/bin/csh

#PBS -N ISTAHW9

#PBS -m bea

#PBS -M rfoitik1@email.arizona.edu

#PBS -W group_list=ericlyons

#PBS -q windfall

#PBS -l jobtype=serial

#PBS -l select=1:ncpus=1:mem=1gb

#PBS -l place=pack:shared

#PBS -l walltime=01:00:00

#PBS -l cput=01:00:00

cd /home/u22/rfoitik1

date
/usr/bin/time echo "This is a test.  Only a test.  Do not panic"
date
